/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f4xx.h"
#include "Config.h"


/**
 * @brief configuracion de la linea EXTI13
 */
void EXTI13_Config(void);


int main(void)
{
	EXTI13_Config();
	/**********************************************/
	RCC->AHB1ENR |= GPIOX_CLOCK(LED);
	GPIOX_MODER(MODE_OUT,LED);
	GPIOX_OSPEEDR(MODE_SPD_VHIGH,LED);
	GPIOX_PUPDR(MODE_PU_NONE,LED);
    /* Loop forever */
	for(;;);
}

/**
 * @brief configuracion de la linea EXTI13
 */
void EXTI13_Config(void){
	/*habilitar el reloj*/
	RCC->AHB1ENR |= GPIOX_CLOCK(LED);
	RCC->APB2ENR |= RCC_APB2ENR_SYSCFGEN;
	/*Configurar el pin PC13*/
	GPIOX_MODER(MODE_DIGITAL_INPUT,BUTTON);
	GPIOX_PUPDR(MODE_PU_NONE,BUTTON);
	/*1. habilitar el bit de enmascaramiento*/
	EXTI->IMR |= EXTI_IMR_IM13;
	/*2. seleccionar el borde de disparo de la IT*/
	EXTI->FTSR |= EXTI_FTSR_TR13;					//IT para exti13 flanco decendente
	/*3. asignar el pin a al linea EXTI1*/
	SYSCFG->EXTICR[3] &=~ SYSCFG_EXTICR4_EXTI13;
	SYSCFG->EXTICR[3] |= SYSCFG_EXTICR4_EXTI13_PC;
	/*4. establecer la prioridad*/
	NVIC_SetPriority(EXTI15_10_IRQn,1);
	/*5. borrar el pending bit*/
	EXTI->PR |= EXTI_PR_PR13;
	NVIC_ClearPendingIRQ(EXTI15_10_IRQn);
	/*6. habilitar la IT en al NVIC*/
	NVIC_EnableIRQ(EXTI15_10_IRQn);
}

/**********************************************************************/
int __io_putchar(int ch){
	ITM_SendChar(ch);
	return ch;
}
