/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "defines.h"
#include "stm32f4xx.h"
#include "USART.h"
#include "delay.h"
#include <string.h>
#include <stdio.h>
/**
 * 0: printf mediante el usart2
 * 1: printf mediante el SWO
 */
#define USE_SWV			0


/**
 * @brief configuracion de pines del USART2
 */
void USART2_GPIOConfig(void);


uint8_t rxBuffer[20];

USART_Handle_t usart2;

int main(void)
{
	delay_Init();
/*******************************************************/
	//LED
	RCC->AHB1ENR |= GPIOX_CLOCK(LED);
	GPIOX_MODER(MODE_OUT,LED);
	//BUTTON
	RCC->AHB1ENR |= GPIOX_CLOCK(BUTTON);
	GPIOX_MODER(MODE_DIGITAL_INPUT,BUTTON);
	GPIOX_PUPDR(MODE_PU_NONE,BUTTON);
/********************************************************/
	USART2_GPIOConfig();
	USART_Init(USART2, 115200);
	//Configuracion de la interrupcion
	usart2.pUSARTx = USART2;
	USART_IRQInterruptConfig(USART2_IRQn, ENABLE);
	USART_IRQPriorityConfig(USART2_IRQn, 1);
/********************************************************/
	USART_ReceiveDataIT(&usart2, rxBuffer, 1);

    /* Loop forever */
	for(;;){
		if(!(GPIOX_IDR(BUTTON))){
			printf("1\r\n");		//si el botton se presiona
		}else{
			printf("0\r\n");		//si no se presiona el botton
		}
		delay_ms(50);				//muestreo cada 50ms
	}
}
/**
 * @brief configuracion de pines del USART2
 */
void USART2_GPIOConfig(void){
	//PA2->USART2_TX , PA3 -> USART2_RX
	RCC->AHB1ENR |= GPIOX_CLOCK(USART2_TX);
	GPIOX_MODER(MODE_ALTER,USART2_TX);
	GPIOX_OSPEEDR(MODE_SPD_VHIGH,USART2_TX);
	GPIOX_AFR(7U,USART2_TX);

	GPIOX_MODER(MODE_ALTER,USART2_RX);
	GPIOX_OSPEEDR(MODE_SPD_VHIGH,USART2_RX);
	GPIOX_AFR(7U,USART2_RX);
	return;
}

/************************************************************/
void USART_ApplicationEventCallback(USART_Handle_t *pUSARTHandle,uint8_t event)
{
	if(USART_EVENT_RX_CMPLT == event){
		if(rxBuffer[0] == '1')
			GPIOX_ODR(LED) = 1;
		else
			GPIOX_ODR(LED) = 0;
	}
	USART_ReceiveDataIT(&usart2, rxBuffer, 1);
}
/************************************************************/
int __io_putchar(int ch){
#if (USE_SWV== 1)
	ITM_SendChar((uint32_t)ch);
#else
	uint8_t c = ch & 0xFF;
	while(!(USART2->SR & USART_SR_TXE));  //espera hasta que usart este listo para transmitir otro byte
	USART2->DR = c;
#endif
	return ch;
}
